[build]
  base = "src/"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

#[[redirects]]
#  from = "/*"
#  to = "https://begin.is/:splat"
#  status = 301
#  force = true