import { defineMessages } from 'react-intl'
import f from "../lib/translate";

const messages = defineMessages({
  artAvatarImgDescription: {
    id: 'artavatar.img.description',
    defaultMessage: 'Image Art generated by AI'
  }
})

type Props = {
  stage: string
  name: string
  picture: string
  description: string
}

const ArtAvatar = ({ stage, name, picture, description }: Props) => {
  return (
    <div className="w-auto inline-block ml-4 p-2 lg:p-8 lg:pl-16 lg:pr-16"
      style={{
        backgroundImage: `url('/images/bg_art_img.png')`,
        backgroundRepeat: 'no-repeat',
        backgroundPositionY: '10px',
        backgroundSize: 'contain',
      }}
    >
      <img src={picture}
        alt="B58 Finance {name}"
        className="w-11/12 object-cover shadow-medium dark:shadow-mediumDark"
      />
      <small className="text-gray-500 uppercase">{f(messages.artAvatarImgDescription)}</small>
      <p className="text-2xl mt-2"><span className="text-4xl mr-2">{stage}</span> {name}</p>
      <p>{description}</p>
    </div>
  )
}

export default ArtAvatar
